name: 'Changelog Generator'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: contains(github.ref, '-') === false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: 0.0.4-featureG.1
          configuration: "./.github/workflows/release_changelog.json"

  prerelease:
    if: contains(github.ref, '-') === false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: 0.0.4-featureG.1
          configuration: "./.github/workflows/prerelease_changelog.json"

